name: CICD

on:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Make build start
        run: echo hello build step
  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - name: Make build start
        run: echo hello build step
  deploy:
    name: Run deploy
    runs-on: ubuntu-latest
    steps:
      - name: Make build start
        run: echo hello build step
